# Generated by Django 2.2.1 on 2019-06-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0002_auto_20190606_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='college_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='college_name',
            new_name='college',
        ),
        migrations.AddField(
            model_name='student',
            name='db_folder',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='isdroppedout',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MockTest1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem1', models.IntegerField()),
                ('problem2', models.IntegerField()),
                ('problem3', models.IntegerField()),
                ('problem4', models.IntegerField()),
                ('total', models.IntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.Student')),
            ],
        ),
    ]
