# Generated by Django 2.2.1 on 2019-06-06 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0003_auto_20190606_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='email',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='isdroppedout',
            new_name='dropped_out',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.College')),
            ],
        ),
    ]
