# Generated by Django 2.2.1 on 2019-06-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balls',
            name='ball',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='batsman',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='batsman_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='batting_team',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='bowler',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='bowling_team',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='bye_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='dismissal_kind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='extra_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='fielder',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='innings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='is_super_over',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='legbye_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='noball_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='non_striker',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='over',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='penalty_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='player_dismissal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='total_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='wide_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='season_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='toss_decision',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='toss_winner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpire1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpire2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpire3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_by_run',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_by_wicket',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
